### ISSUE TITLE
How to bind the dn in the authentication

### ISSUE THREAD

**Issue by narendrachoudhary** [joewalnes/node-ldapauth#11]
Hi Joe,

how can i use the bind dn and password to authenticate on the Openldap server. I was used the java code and that was working fine but here i am not able to find the binddn enteries to be passed to the authenticate function. Any help would be a great help for me...

**Comment by joewalnes** [comment]
This library does not support bind DN. You can only use host, username and password.

I would recommend http://ldapjs.org/client.html instead.
